"""initial schema

Revision ID: 884060676c54
Revises:
Create Date: 2026-09-13 22:29:28.093452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884060676c54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefix_map',
    sa.Column('prefix_code', sa.String(length=32), nullable=False),
    sa.Column('voivodeship_teryt', sa.String(length=2), nullable=False),
    sa.Column('voivodeship_name', sa.Text(), nullable=False),
    sa.Column('powiat_teryt', sa.String(length=4), nullable=True),
    sa.Column('powiat_name', sa.Text(), nullable=True),
    sa.Column('gmina_teryt', sa.String(length=7), nullable=True),
    sa.Column('gmina_name', sa.Text(), nullable=True),
    sa.Column('district_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('prefix_code')
    )
    op.create_index('ix_prefix_map_gmina', 'prefix_map', ['gmina_teryt'], unique=False)
    op.create_index('ix_prefix_map_powiat', 'prefix_map', ['powiat_teryt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prefix_map_powiat', table_name='prefix_map')
    op.drop_index('ix_prefix_map_gmina', table_name='prefix_map')
    op.drop_table('prefix_map')
    # ### end Alembic commands ###
