"""add run_id,territory_code,error_trace

Revision ID: 78c640067803
Revises: 53ee61e57123
Create Date: 2026-09-21 19:33:18.162384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c640067803'
down_revision: Union[str, Sequence[str], None] = '53ee61e57123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ENUM_NAME = "taskstatusenum"
NEW_VALUES = ("cleaning", "joining", "done", "not_published")


def upgrade() -> None:
    existing = {
        row[0]
        for row in op.get_bind().execute(
            sa.text("SELECT enumlabel FROM pg_enum WHERE enumtypid = CAST(:t AS regtype)"),
            {"t": ENUM_NAME},
        )
    }
    with op.get_context().autocommit_block():
        for value in NEW_VALUES:
            if value not in existing:
                op.execute(f"ALTER TYPE {ENUM_NAME} ADD VALUE '{value}'")

    op.add_column('task_status', sa.Column('run_id', sa.Uuid(), nullable=True))
    op.add_column('task_status', sa.Column('territory_code', sa.String(length=4), nullable=True))
    op.add_column('task_status', sa.Column('error_trace', sa.Text(), nullable=True))
    op.alter_column('task_status', 'failed_stage',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_task_status_run_id'), 'task_status', ['run_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_run_id'), table_name='task_status')
    op.alter_column('task_status', 'failed_stage',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('task_status', 'error_trace')
    op.drop_column('task_status', 'territory_code')
    op.drop_column('task_status', 'run_id')
    # ### end Alembic commands ###
