"""add staged_transactions

Revision ID: 905f9dc7d6b8
Revises: 78c640067803
Create Date: 2026-09-28 20:15:07.845697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '905f9dc7d6b8'
down_revision: Union[str, Sequence[str], None] = '78c640067803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staged_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('source_local_id', sa.String(length=64), nullable=False),
    sa.Column('premises_id', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=32), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('price_premises', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('area_usable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('market_type', sa.String(length=32), nullable=True),
    sa.Column('function', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('powiat_code', sa.String(length=4), nullable=False),
    sa.Column('gmina_code', sa.String(length=7), nullable=True),
    sa.Column('city_name', sa.Text(), nullable=True),
    sa.Column('district_name', sa.Text(), nullable=True),
    sa.Column('exclusion_reason', sa.String(length=32), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_local_id', 'premises_id', name='uq_staged_transactions_key', postgresql_nulls_not_distinct=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staged_transactions')
    # ### end Alembic commands ###
